version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  post_build:
    commands:
      - mvn package
      - mv target/app-0.0.1-SNAPSHOT.jar app-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - app-0.0.1-SNAPSHOT.jar
    - .ebextensions/**/*